name: push-tag

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # We need history to determine oasis-node version from git tag.
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Compute version
        # Version image by tag.
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0); echo "VERSION=${LATEST_TAG//v/}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{ env.VERSION }}
          context: .
          file: Dockerfile
          tags: |
            munaynetwork/oasis-node:latest
            munaynetwork/oasis-node:${{ env.VERSION }}
          push: true
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
